# Binance Futures PRODUCTION Configuration
# ⚠️  WARNING: THIS USES REAL MONEY - USE TESTNET FOR TESTING ⚠️
# For risk-free testing, use binance_futures_testnet.yaml instead
# Environment variables can be referenced with ${VAR_NAME}

venue:
  name: BINANCE
  venue_type: futures
  account_type: PERPETUAL_LINEAR

# API Configuration - PRODUCTION
api:
  api_key: ${BINANCE_API_KEY:-BACKTEST_MODE}  # Default for backtests
  api_secret: ${BINANCE_API_SECRET:-BACKTEST_MODE}  # Default for backtests
  testnet: false  # Set to true for testnet (or use binance_futures_testnet.yaml)
  base_url: https://fapi.binance.com  # Production URL

# Trading Configuration
trading:
  hedge_mode: true  # Enable hedge mode for long/short positions simultaneously
  leverage: 10
  margin_type: CROSSED  # CROSSED or ISOLATED

# Risk & Precision Guards
risk:
  max_leverage: 20
  min_order_size_usdt: 5.0
  max_order_size_usdt: 100000.0

precision:
  price_precision: 2
  quantity_precision: 3
  min_notional: 5.0

# Rate Limits
rate_limits:
  orders_per_second: 5
  orders_per_minute: 100
  weight_per_minute: 1200

# WebSocket Configuration
websocket:
  ping_interval: 20
  reconnect_timeout: 60
  max_reconnect_attempts: 5

# Instruments to load and trade
symbols:
  - BTCUSDT-PERP
  - ETHUSDT-PERP
