# Binance Futures TESTNET Configuration
# Use this for risk-free testing with fake funds
# Get testnet API keys from: https://testnet.binancefuture.com

venue:
  name: BINANCE
  venue_type: futures
  account_type: PERPETUAL_LINEAR

# API Configuration - TESTNET
#
# How this works:
# - testnet: true → Nautilus auto-detects HTTP URL as https://testnet.binancefuture.com
# - base_url: null → Use Nautilus auto-detection (recommended)
# - ws_url: wss://fstream.binancefuture.com → Override Nautilus bug
#
# NOTE: Nautilus 1.220.0 has a bug where testnet WebSocket URL is set to
#       wss://stream.binancefuture.com (missing 'f' prefix), which causes
#       403 Forbidden errors. We override it here with the correct URL.
api:
  api_key: ${BINANCE_TESTNET_API_KEY}
  api_secret: ${BINANCE_TESTNET_API_SECRET}
  testnet: true
  base_url: null  # Auto-detected by Nautilus when testnet=true
  ws_url: wss://fstream.binancefuture.com  # Fix for Nautilus bug (should be fstream, not stream)

# Trading Configuration
trading:
  hedge_mode: true  # Enable hedge mode for long/short positions simultaneously
  leverage: 10
  margin_type: CROSSED  # CROSSED or ISOLATED

# Risk & Precision Guards
risk:
  max_leverage: 20
  min_order_size_usdt: 5.0
  max_order_size_usdt: 100000.0

precision:
  price_precision: 2
  quantity_precision: 3
  min_notional: 5.0

# Rate Limits (testnet may have different limits)
rate_limits:
  orders_per_second: 5
  orders_per_minute: 100
  weight_per_minute: 1200

# WebSocket Configuration
websocket:
  ping_interval: 20
  reconnect_timeout: 60
  max_reconnect_attempts: 5

# Instruments to load and trade
symbols:
  - BTCUSDT-PERP
  - ETHUSDT-PERP
