# Backtest Configuration for BTCUSDT with Mark/Trades/Funding Data

backtest:
  name: btcusdt_mark_trades_funding
  description: BTC perpetual backtest with mark price, trades, and funding rates

# Time Range
time_range:
  start_time: "2024-01-01T00:00:00Z"
  end_time: "2024-02-01T00:00:00Z"
  timezone: UTC

# Data Configuration
data:
  catalog_path: ./data/catalog

  # Instruments to load
  instruments:
    - instrument_id: BTCUSDT-PERP.BINANCE
      data_types:
        - type: Bar  # 1-minute mark price bars (fast download)
        - type: FundingRate

  # Data sources
  sources:
    - type: parquet
      path: ./data/binance/futures/btcusdt/
      glob_pattern: "*.parquet"

# Venue Configuration
venues:
  - config_path: ./configs/venues/binance_futures.yaml
    starting_balances:
      - currency: USDT
        total: 10000.0
        locked: 0.0

# Strategies to Run
strategies:
  - config_path: ./configs/strategies/hedge_grid_v1.yaml
    enabled: true

# Execution Simulation
execution:
  # Latency modeling
  latency:
    order_submit_ms: 50
    order_cancel_ms: 30
    fill_mean_ms: 100
    fill_std_ms: 20

  # Fill simulation
  fill_model:
    type: naive  # naive, realistic, or probabilistic
    maker_fill_prob: 1.0  # Probability maker orders fill
    aggressive_fill_prob: 1.0
    slippage_bps: 0.0  # Expected slippage in bps

  # Fees
  fees:
    maker_bps: 2.0  # 0.02% maker fee
    taker_bps: 5.0  # 0.05% taker fee
    funding_apply: true  # Apply funding rate costs

# Risk Controls
risk:
  max_drawdown_pct: 20.0
  max_daily_loss_pct: 5.0
  stop_on_liquidation: true

# Logging & Output
output:
  report_dir: ./reports
  save_trades: true
  save_positions: true
  save_account_state: true
  log_level: INFO  # Console logging level (DEBUG, INFO, WARNING, ERROR)
  log_level_file: INFO  # File logging level (set to null to disable file logging)
  log_file_format: text  # Log file format: text or json

# Performance Metrics
metrics:
  calculate:
    - sharpe_ratio
    - sortino_ratio
    - max_drawdown
    - calmar_ratio
    - win_rate
    - profit_factor
    - avg_trade_pnl
    - total_trades
    - funding_pnl

  risk_free_rate: 0.04  # 4% annual risk-free rate
  periods_per_year: 365  # Daily returns
