strategy:
  name: hedge_grid_v1
  instrument_id: BTCUSDT-PERP.BINANCE
grid:
  grid_step_bps: 100.0
  grid_levels_long: 9
  grid_levels_short: 6
  base_qty: 0.0011285819541700388
  qty_scale: 1.1
exit:
  tp_steps: 5
  sl_steps: 5
rebalance:
  recenter_trigger_bps: 300.0
  max_inventory_quote: 10000.0
execution:
  maker_only: true
  use_post_only_retries: true
  retry_attempts: 3
  retry_delay_ms: 100
funding:
  funding_window_minutes: 480
  funding_max_cost_bps: 10.0
regime:
  adx_len: 18
  ema_fast: 7
  ema_slow: 60
  atr_len: 12
  hysteresis_bps: 30.0
position:
  max_position_size: 0.1
  max_position_pct: 0.95
  max_leverage_used: 5.0
  emergency_liquidation_buffer: 0.15
policy:
  strategy: throttled-counter
  counter_levels: 3
  counter_qty_scale: 0.5
